// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'card_body': string;
  'card_body_description': string;
  'card_body_img': string;
  'card_btn': string;
  'card_btns': string;
  'content': string;
  'countMe': string;
  'user_desciption': string;
  'user_info': string;
  'wraper': string;
}
export const cssExports: CssExports;
export default cssExports;
