// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contaner_form': string;
  'error': string;
  'modal_btn': string;
  'modal_form': string;
  'modal_header': string;
  'modal_icon_pass': string;
  'modal_input': string;
  'modal_label': string;
  'modal_link': string;
  'modal_text': string;
  'text_error': string;
}
export const cssExports: CssExports;
export default cssExports;
