// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card_btn': string;
  'card_btns': string;
  'celender_error': string;
  'container': string;
  'hotel_room': string;
  'text': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
