// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chat': string;
  'chat_input': string;
  'chat_input_btn': string;
  'chat_input_textarea': string;
  'container': string;
  'header_support': string;
  'text': string;
  'title': string;
  'title_chat': string;
  'wraper': string;
}
export const cssExports: CssExports;
export default cssExports;
