version: '1.0'

services:
  diplom:
    build: .
    ports:
      - 80:3000
      - 3000:3001
    environment:
      - PORT=3000   
      - PORT=3001   
    depends_on:      
      - mongo
      - mongo-express  
    volumes:     
      - ./public:/diplom/app/public
     
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
   
    ports:
      - '27017:27017'
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
   

volumes:
  dbdata:
  node_modules: 


   