// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error': string;
  'form': string;
  'form_btn': string;
  'form_input': string;
  'form_label': string;
  'label_text': string;
  'limit': string;
  'offset': string;
  'search': string;
  'text_error': string;
}
export const cssExports: CssExports;
export default cssExports;
