// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'btn_icons': string;
  'btn_icons_close': string;
}
export const cssExports: CssExports;
export default cssExports;
