// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'btn_logout': string;
  'icons': string;
  'link': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
