// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'list': string;
  'list_img': string;
  'list_item': string;
  'sidebar': string;
}
export const cssExports: CssExports;
export default cssExports;
