// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'container': string;
  'create_support': string;
  'icons_btn': string;
  'menu': string;
  'search_support': string;
  'title': string;
  'wraper': string;
}
export const cssExports: CssExports;
export default cssExports;
