// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'paginator_switcher': string;
  'paginator_wraper': string;
  'paginator_wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
