// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'hotel': string;
  'text': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
