// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'card_body': string;
  'card_body_description': string;
  'card_body_title': string;
  'card_body_wrapper': string;
  'card_btn': string;
  'card_btns': string;
  'card_img': string;
}
export const cssExports: CssExports;
export default cssExports;
