// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form': string;
  'form_btn': string;
  'form_input': string;
  'form_label': string;
  'form_label_title': string;
  'label_text': string;
  'label_text_id': string;
  'limit': string;
  'offset': string;
}
export const cssExports: CssExports;
export default cssExports;
