// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'card': string;
  'description': string;
  'title': string;
  'title_id': string;
}
export const cssExports: CssExports;
export default cssExports;
