// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'col_index': string;
  'col_text': string;
  'container': string;
  'table': string;
}
export const cssExports: CssExports;
export default cssExports;
