// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'message_date': string;
  'message_header': string;
  'message_left': string;
  'message_right': string;
  'message_right_noread': string;
  'message_text': string;
  'message_user': string;
}
export const cssExports: CssExports;
export default cssExports;
