// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'container': string;
  'create_user': string;
  'icons_btn': string;
  'menu': string;
  'search': string;
  'title': string;
  'user_container': string;
}
export const cssExports: CssExports;
export default cssExports;
