// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form': string;
  'form_btn': string;
  'form_input': string;
  'form_label': string;
  'form_textarea': string;
  'image_btn': string;
  'image_btn_wrap': string;
  'image_item': string;
  'image_modal': string;
  'image_wraper': string;
  'image_wraper_modal': string;
  'images_list': string;
  'input_file': string;
  'input_file_btn': string;
  'input_file_text': string;
  'photo_preview': string;
  'title_img': string;
}
export const cssExports: CssExports;
export default cssExports;
