// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn_close': string;
  'icon_cross': string;
  'reservations': string;
  'reservations_header': string;
  'reservations_item': string;
  'text': string;
  'text_data_end': string;
  'text_data_start': string;
  'text_hotel': string;
  'text_id': string;
  'text_remove': string;
  'visually_hidden': string;
}
export const cssExports: CssExports;
export default cssExports;
