// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'calendar_end': string;
  'calendar_start': string;
  'calendar_wrapper': string;
  'container': string;
  'select': string;
  'text_error': string;
}
export const cssExports: CssExports;
export default cssExports;
